version: '3.9'

services:
  laravel-app:
    build:
      context: ./laravel-app
      dockerfile: Dockerfile-ngnix       # Select to run on Ngnix Webserver
#      dockerfile: Dockerfile-apache      # Select to run on Apache Webserver
    ports:
      - "8080:80"
    environment:
      - APP_ENV=local
#      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=sarasai_lms
      - DB_USERNAME=sarasai_lms
      - DB_PASSWORD=eqnz%ykp66R@E6F
    volumes:
      - ./laravel-app:/var/www                   # Select to run on Ngnix Webserver
#      - ./laravel-app:/var/www/html              # Select to run on Apache Webserver
    restart: always
    depends_on:
      db:
        condition: service_healthy

  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: always
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - laravel-app
    volumes:
      - ./react-app:/app

  db:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_DATABASE: sarasai_lms
      MYSQL_USER: sarasai_lms
      MYSQL_PASSWORD: eqnz%ykp66R@E6F
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    depends_on:
      - phpmyadmin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
