FROM php:8.2-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    nginx

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Get Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www

# Copy existing application directory contents
COPY . /var/www

# Install dependencies
RUN composer install --no-dev --optimize-autoloader

# Copy Nginx configuration
#COPY ngnix/nginx.conf /etc/nginx/sites-available/default
COPY ngnix/laravel.conf /etc/nginx/nginx.conf

# Change ownership of our applications
RUN chown -R www-data:www-data /var/www
RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache
RUN chmod -R 777 /var/www/storage /var/www/bootstrap/cache

RUN echo "listen = 9000" >> /usr/local/etc/php-fpm.d/www.conf

# Expose port 80
EXPOSE 80

# Start Nginx & PHP-FPM
#CMD service nginx start && php-fpm
#CMD php-fpm -D && nginx -g 'daemon off;'
CMD php-fpm -D && echo "PHP-FPM started" && nginx -g 'daemon off;' > /var/log/nginx/startup.log 2>&1

COPY entrypoint-ngnix.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint-ngnix.sh

# Set the entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint-ngnix.sh"]
